{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ticketforge.fullname" . }}-default-deny-ingress
spec:
  podSelector: {}
  policyTypes: [Ingress]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ticketforge.fullname" . }}-allow-gateway
spec:
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values: [web, api]
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              gateway.networking.k8s.io/gateway-name: {{ include "ticketforge.fullname" . }}-gateway
      ports:
        - { protocol: TCP, port: {{ .Values.api.port }} }
        - { protocol: TCP, port: {{ .Values.frontend.port }} }
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ticketforge.fullname" . }}-allow-api-to-data
spec:
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values: [database, cache, broker]
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: api
      ports:
        - { protocol: TCP, port: 5432 }
        - { protocol: TCP, port: 6379 }
        - { protocol: TCP, port: 9092 }
{{- if .Values.frontend.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ticketforge.fullname" . }}-allow-chart-test
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ticketforge.fullname" . }}-frontend
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: test
      ports:
        - { protocol: TCP, port: {{ .Values.frontend.port }} }
{{- end }}
{{- end }}
