apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
labels:
  - pairs:
      app.kubernetes.io/environment: development
images:
  - name: ticketforge-api
    newName: ticketforge-api
    newTag: sprint-19
  - name: ticketforge-frontend
    newName: ticketforge-frontend
    newTag: sprint-20-networking-v2
