export interface StudyDay {
  day: number;
  week: number;
  title: string;
  focus: string;
  domain: string;
  route?: string;
  evidence: string;
}

export const CLF_C02_STUDY_PLAN: StudyDay[] = [
  { day: 1, week: 1, title: 'Cloud foundations & global infrastructure', focus: 'Learn how Regions, Availability Zones, edge locations, elasticity, and shared responsibility affect a cloud application.', domain: 'Cloud Concepts', route: '/academy/aws/cloud-practitioner/cloud-foundations', evidence: 'Draw where TicketForge would run and explain how it survives one Availability Zone failure.' },
  { day: 2, week: 1, title: 'Identity & account security', focus: 'Learn when to use the root user, IAM Identity Center, roles, policies, MFA, and temporary credentials.', domain: 'Security & Compliance', route: '/academy/aws/cloud-practitioner/lab-zero', evidence: 'Show which identity runs your TicketForge AWS commands without exposing a credential.' },
  { day: 3, week: 1, title: 'EC2 & compute economics', focus: 'Learn how EC2 instances, images, storage, security groups, Auto Scaling, load balancers, and purchasing models work together.', domain: 'Technology & Services', evidence: 'Choose compute and pricing for TicketForge when normal traffic is low but event traffic creates large spikes.' },
  { day: 4, week: 1, title: 'Containers & serverless', focus: 'Compare Lambda, ECS, Fargate, EKS, and EC2 by asking who manages the servers, scaling, and application runtime.', domain: 'Technology & Services', evidence: 'Choose where the TicketForge API should run and explain why the other compute options are weaker for that scenario.' },
  { day: 5, week: 1, title: 'Storage choices', focus: 'Learn when an application needs object, block, or shared file storage and how encryption, versioning, lifecycle rules, and storage classes change the design.', domain: 'Technology & Services', evidence: 'Choose storage for TicketForge event images, database disks, and shared application files.' },
  { day: 6, week: 1, title: 'Review the first five days', focus: 'Answer 30–50 questions about cloud foundations, identity, compute, containers, and storage.', domain: 'Mixed', evidence: 'Write down why each missed answer was wrong instead of recording only the score.' },
  { day: 7, week: 1, title: 'Fix your weakest topic', focus: 'Review only the concepts that your questions showed you do not understand yet.', domain: 'Review', evidence: 'Explain one previously missed concept with a new TicketForge example and without reading notes.' },
  { day: 8, week: 2, title: 'AWS networking', focus: 'Learn how a VPC, public and private subnets, routes, gateways, security groups, network ACLs, and load balancers move and protect traffic.', domain: 'Technology & Services', evidence: 'Trace a customer request from the internet to a TicketForge API running in a private subnet.' },
  { day: 9, week: 2, title: 'Database choices', focus: 'Compare RDS, Aurora, DynamoDB, ElastiCache, and Redshift by workload, scaling, availability, and operational responsibility.', domain: 'Technology & Services', evidence: 'Choose services for TicketForge transactions, caching, and analytics, and explain why one database should not do every job.' },
  { day: 10, week: 2, title: 'Application integration', focus: 'Learn how SQS, SNS, EventBridge, and Step Functions decouple work and route messages between services.', domain: 'Technology & Services', evidence: 'Choose a queue, notification topic, or event bus for TicketForge reservation, email, and analytics scenarios.' },
  { day: 11, week: 2, title: 'DNS & content delivery', focus: 'Learn how Route 53 finds an application and how CloudFront or Global Accelerator can improve delivery to distant users.', domain: 'Technology & Services', evidence: 'Trace how a customer finds TicketForge and receives a cached event image.' },
  { day: 12, week: 2, title: 'Monitoring & governance', focus: 'Compare CloudWatch, CloudTrail, Config, Trusted Advisor, Organizations, Control Tower, and Systems Manager by the question each service answers.', domain: 'Security & Compliance', evidence: 'Choose the service that shows TicketForge metrics, the identity that changed a resource, and a configuration that became noncompliant.' },
  { day: 13, week: 2, title: 'Review the architecture choices', focus: 'Read TicketForge requirements, choose matching AWS services, and complete 40–60 scenario questions.', domain: 'Mixed', evidence: 'For every service you select, name one alternative and explain why you rejected it.' },
  { day: 14, week: 2, title: 'Fix your weakest topic', focus: 'Use your results to review only the service boundaries you still confuse.', domain: 'Review', evidence: 'Answer new scenarios about those boundaries without memorizing the previous answers.' },
  { day: 15, week: 3, title: 'Security services', focus: 'Learn which AWS services protect secrets and data, detect threats, inspect workloads, block attacks, and provide compliance information.', domain: 'Security & Compliance', evidence: 'Choose security services for TicketForge secrets, encryption keys, suspicious activity, web attacks, and compliance reports.' },
  { day: 16, week: 3, title: 'Pricing models', focus: 'Compare On-Demand, Spot, reservations, Savings Plans, data transfer, and Free Tier by commitment and interruption tolerance.', domain: 'Billing & Support', evidence: 'Choose pricing for steady TicketForge databases, flexible API capacity, and interruptible background work.' },
  { day: 17, week: 3, title: 'Billing & cost management', focus: 'Learn which tool estimates future cost, reports past cost, sends threshold alerts, and organizes spending across accounts.', domain: 'Billing & Support', evidence: 'Estimate TicketForge before deployment, then explain how you would monitor its real spending.' },
  { day: 18, week: 3, title: 'Well-Architected Framework', focus: 'Use the six Well-Architected pillars to review operations, security, reliability, performance, cost, and sustainability.', domain: 'Cloud Concepts', evidence: 'Review TicketForge against all six pillars and propose one specific improvement.' },
  { day: 19, week: 3, title: 'Take a timed practice exam', focus: 'Complete one full exam without interruptions so the score reflects your current recall and decision speed.', domain: 'Assessment', evidence: 'Record the score and classify every missed question before reading its explanation.' },
  { day: 20, week: 3, title: 'Review only the remaining gaps', focus: 'Study the weak domains and service pairs identified by the timed exam.', domain: 'Review', evidence: 'Reach at least 80% on a new assessment that does not reuse the same questions.' },
  { day: 21, week: 3, title: 'Decide whether you are ready', focus: 'Review your domain coverage, lab completion, cleanup, explanations, and practice scores before scheduling the exam.', domain: 'Assessment', evidence: 'Make a go or no-go decision and support it with your recorded results.' },
];
